print("Lisa")
print("Peter,Georg,Kathi,Lias")
print("Peter")
print("Georg")
print("Kathi")
print("Lisa")
hallo = input("Hallo wie gehts? ")
age = input("Wie alt bist du? ")
print(int(age))
gender = input("Welches Geschlecht bist du? ")